version: "3.9"

services:
  db:
    image: postgres:16
    container_name: pm_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pm_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build: .
    container_name: pm_api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      APP_JWT_SECRET: ${APP_JWT_SECRET}
      APP_JWT_TTLMINUTES: ${APP_JWT_TTLMINUTES}

      HOME: /home/appuser
    volumes:
      - pm_uploads:/home/appuser/pm_uploads
    ports:
      - "8081:8080"
    restart: unless-stopped

volumes:
  pm_pgdata:
  pm_uploads:
